OrganizationsWebApplication/Controllers/ImportExportController.cs
using System;
using System.Linq;
using System.ServiceModel;
using System.Xml;
using System.Xml.Linq;
using Newtonsoft.Json;
using NLog;
using System.Web.Mvc;
using Organizations;
using Organizations.Container;


namespace OrganizationsWebApplication.Controllers
{
    public class ImportExportController : Controller
    {
        private Facade m_facade = ContainerWrapper.Container.GetInstance<Facade>();
        private static Logger logger = LogManager.GetCurrentClassLogger();

        public ActionResult MainMenu()
        {
            return View();
        }
        
        public string GetFile(string fileName)
        {
            var fileService = new TcpXmlService.XmlServiceClient("NetTcpBinding_IXmlService");
            var file = fileService.LoadXmlFile(fileName);
            return file;
        }
        
        public JsonResult Import(string fileName)
        {
            //var fileService = MvcContainer.Container.GetInstance<WcfService.Service>();
            var fileService = new TcpXmlService.XmlServiceClient("NetTcpBinding_IXmlService");

            string result = null;
            try
            {
                var stringDocument = fileService.LoadXmlFile(fileName);
                var xDocument = XDocument.Parse(stringDocument);

                var xmlDocument = new XmlDocument();
                using (var reader = xDocument.CreateReader())
                {
                    xmlDocument.Load(reader);
                }
                var converted = JsonConvert.SerializeXmlNode(xmlDocument);
                result = converted.Replace("@", "");
            }
            catch (FaultException ex)
            {
                logger.Error(ex.Message);
                result = ex.Message;
            }
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        

        public string Export()
        {
            var doc = new XDocument();
            var root = new XElement("root");
            doc.Add(root);

            var organizationsList = m_facade.GetAllOrganizations();

            foreach (var org in organizationsList)
            {
                var organization = new XElement("organization");

                organization.Add(new XAttribute("Id", org.Id));
                organization.Add(new XAttribute("Name", org.Name));

                var departmentsList = m_facade.GetAllDepartments().Where(x => x.ParentOrganization.Id == org.Id);

                foreach (var dep in departmentsList)
                {
                    var department = new XElement("department");
                    department.Add(new XAttribute("Id", dep.Id));
                    department.Add(new XAttribute("Name", dep.Name));

                    var employeesList = m_facade.GetAllEmployees().Where(y => y.ParentDepartment != null).Where(x => x.ParentDepartment.Id == dep.Id);
                    foreach (var emp in employeesList)
                    {
                        var employee = new XElement("employee");
                        employee.Add(new XAttribute("Id", emp.Id));
                        employee.Add(new XAttribute("Name", emp.Name));

                        department.Add(employee);
                    }
                    organization.Add(department);
                }
                root.Add(organization);
            }

            //var fileService = MvcContainer.Container.GetInstance<WcfService.Service>();
            var fileService = new TcpXmlService.XmlServiceClient("NetTcpBinding_IXmlService");

            try
            {
                //fileService.SaveXmlFile(doc, "file.xml");
                var fileName = DateTime.Now.ToString("yyyy-MM-dd HH.mm.ss");
                fileService.SaveXmlFile(doc.ToString(), fileName);
                return fileName;
            }
            catch (FaultException ex)
            {
                logger.Error(ex.Message);
                return null;
            }

        }
    }
}

OrganizationsWebApplication/Views/_AccountBar.cshtml
@using System.Web.Mvc.Html
@using OrganizationsWebApplication.LocalResource
<div class="userMenu">
    <nav>
        <ul>
            <li>
                <a class="dropdown" href="#">@WebSecurity.CurrentUserName</a>
                <ul>
                    <li>
                        @Html.ActionLink(Resource.Logout, "Logout", "Account")
                    </li>

                    @if (Roles.IsUserInRole("admin"))
                    {
                        <li>
                            @Html.ActionLink(Resource.Administration, "AdministrationInfo", "Administration")
                        </li>
                        
                        <li>
                            @Html.ActionLink("Import/Export", "MainMenu", "ImportExport")
                        </li>

                    }
                </ul>
            </li>
        </ul>
    </nav>
</div>

OrganizationsWebApplication/Views/_AccountPanel.cshtml
<div class="userMenu">
    <nav>
        <ul>
            <li>
                <a class="dropdown" href="#">@WebSecurity.CurrentUserName</a>
                <ul>
                    <li>
                        @Html.ActionLink("Logout", "Logout", "Account")
                    </li>

                    @if (Roles.IsUserInRole("admin"))
                    {
                        <li>
                            @Html.ActionLink("Administration", "Administration", "Account")
                        </li>
                    }
                </ul>
            </li>
        </ul>
    </nav>
</div>

OrganizationsWebApplication/Views/_GlobalizationBar.cshtml
@model OrganizationsWebApplication.Models.PagesModels.BaseViewModel

@{
    string rawUrl = Request.RawUrl;

    string newUrlRu = rawUrl.Replace("/en/", "/ru/");
    <a href="@newUrlRu" title="Culture">RU</a>

    string newUrlEn = rawUrl.Replace("/ru/", "/en/");
    <a href="@newUrlEn" title="Culture">EN</a>
}

OrganizationsWebApplication/Views/_MainCommandsBar.cshtml
@using OrganizationsWebApplication.Helpers
@using System.Web.Mvc.Html
@model OrganizationsWebApplication.Models.PagesModels.BaseViewModel

@{
    var helper = new MainCommandsViewHelper(Model);
}

<span class="operationBlock" style="background: #3F51B5; width: 600px; height: 50px">
    
    <form>
        <img src="../../Content/view-list.svg" onclick=" switchView() " style="cursor: pointer;" />
    </form>
    
    @if (helper.GoHomeController != null)
    {
        using (Html.BeginForm(helper.GoHomeAction, helper.GoHomeController, new
    {
        id = @Model.viewCondition.ParentId,
        Model.viewCondition.CurrentPageNumber,
        Model.viewCondition.SortType
    }, FormMethod.Post))
        {
            <input type="image" src="../../Content/ic_home_24px_inverse.svg" alt="home" name="submit" />
        }
    }
    
    @using (Html.BeginForm(helper.ChangeSortingAction, helper.ControllerName, new
    {
        id = Model.viewCondition.Id,
        Model.viewCondition.CurrentPageNumber,
        Model.viewCondition.SortType
    }, FormMethod.Post))
    {
        if (Model.viewCondition.SortType == "desc")
        {
            <input type="image" src="../../Content/sort-ascending.svg" alt="sort" name="submit" />
        }

        if (Model.viewCondition.SortType == "asc")
        {
            <input type="image" src="../../Content/sort-descending.svg" alt="sort" name="submit" />
        }
    }
 
    @if (Roles.IsUserInRole("admin") && (Model.viewCondition.PageType != "dep_info"))
    {
        using (Html.BeginForm(helper.AddNewEntityAction, helper.ControllerName, new
    {
        id = @Model.viewCondition.Id,
        Model.viewCondition.CurrentPageNumber,
        Model.viewCondition.SortType
    }, FormMethod.Post))
        {
            <input style="background: #3F51B5" type="image" src="../../Content/ic_add_box_24px_inverse.svg" alt="add" name="submit" />
        }
    }
  
</span>

OrganizationsWebApplication/Views/_PagingBar.cshtml
@using OrganizationsWebApplication.Helpers
@model OrganizationsWebApplication.Models.PagesModels.BaseViewModel

@{
    var helper = new MainCommandsViewHelper(Model);
}

<span class="operationBlock" style="background: #000; width: 600px; height: 50px; margin-top: -50px;display: block;">

    @using (Html.BeginForm(helper.GoPrevPageAction, helper.ControllerName, new
        {
            id = @Model.viewCondition.Id,
            Model.viewCondition.CurrentPageNumber,
            Model.viewCondition.SortType
        }))
    {
        <input type="image" src="../../Content/ic-double-left.svg" name="submit" style="cursor: pointer;" />
    }
    <form>
        <span style="font-family: RobotoDraft, Roboto, sans-serif; font-size: 20px; color: #ffffff;">
            @Model.viewCondition.CurrentPageNumber / @Model.viewCondition.MaxPageNumber
        </span>
    </form>
    @using (Html.BeginForm(helper.GoNextPageAction, helper.ControllerName, new
            {
                id = @Model.viewCondition.Id,
                Model.viewCondition.CurrentPageNumber,
                Model.viewCondition.SortType
            }))
    {
        <input type="image" src="../../Content/ic-double-right.svg" name="submit" style="cursor: pointer;" />
    }

</span>